### ISSUE TITLE
Issues with binary

### ISSUE THREAD

**Issue by Jocadbz** [Jocadbz/shellpkg#19]
It appears we have several issues and tracebacks. Listing them:

```Traceback (most recent call last):
  File "pypkg.py", line 110, in <module>
  File "pypkg.py", line 94, in DO_WORK
  File "pypkg.py", line 59, in INSTALL
NameError: name 'exit' is not defined
[488974] Failed to execute script 'pypkg' due to unhandled exception!```

**Comment by Jocadbz** [comment]
_Ahem_, i'm deeply sorry for my dumbness. `exit` it's not even defined.

**Comment by Jocadbz** [comment]
Fixed. Lol
